### ISSUE TITLE
No stream output from webcam. No errors raised.

### ISSUE THREAD

**Issue by hernandosalas** [alexyak/camera#12]
Hi,

I'm trying to use a USB Logitech webcam on my raspberry pi 4 running a magic mirror. I tested the webcam via a webcam test website in my raspberry pi and it works; however, it doesn't in the magic mirror nothing displays. This is what I tried so far:

- Added camera module to config.js
- Changed in camera.js  -> display: true
- updated my raspberry pi
- updated magic mirror

- node version in raspberry pi is 14.15.0

![image](https://user-images.githubusercontent.com/41709599/98123185-853d5080-1e7f-11eb-8254-98f228589c44.png)

Any help or advice is greatly appreciated. Thank you in advance.

**Comment by yax51** [comment]
Did you get this fixed? I am having the exact same issue, and tried the exact same things.
If so, can you provide the solution?
Thanks!

**Comment by IshanDindorkar** [comment]
I am also facing this issue. Tried solutions mentioned in the forum but it didn't helped. I would appreciate if you both could please share your insights if you found some workaround. Thank you in advance!
